FROM qgis/qgis:release-3_36
# FROM qgis/qgis:3.40.10

# set up plugin path
# ENV QGIS_PLUGINPATH=/root/.local/share/QGIS/QGIS3/profiles/default/python/plugins
ENV QGIS_PLUGINPATH=/QGIS/build/output/python/plugins

# copy arches_project plugin to container
COPY . ./ 

WORKDIR arches_project

ENV PYTHONPATH=$PYTHONPATH:/arches_project/tests:$QGIS_PLUGINPATH

ENV XDG_RUNTIME_DIR=/tmp

# Copy test runner file(s) as missing from later images 
# COPY test/qgis_docker_test_runners/qgis_testrunner.sh /usr/bin 
# COPY test/qgis_docker_test_runners/qgis_testrunner.py /usr/bin 
# COPY test/qgis_docker_test_runners/qgis_setup.sh /usr/bin 
# COPY test/qgis_docker_test_runners/qgis_startup.py /usr/bin

# Run integration tests by using the test script
RUN xvfb-run qgis_testrunner.sh plugin_tests