name: Arches QGIS Plugin Tests

on: 
  # push: -- just run on PRs for now
  pull_request:
  workflow_dispatch:

jobs:
  build_target_branch:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        # run on QGIS LTR
        qgis_version: [3.40.11]

    steps:
      - uses: actions/checkout@v4

      - name: Checkout into target branch
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.event.pull_request.base.ref }}
          path: .

      - name: Set up Arches
        uses: ./.github/actions/build-arches-environment

      - name: Set up QGIS ${{ matrix.qgis_version }}
        uses: ./.github/actions/build-qgis-environment
        with:
          qgis_version: ${{ matrix.qgis_version }}

      - name: Run black formatting
        run: |
          docker exec qgis-testing-environment bash -c "cd /tests_directory/arches_project && pre-commit run --all-files --verbose"

      - name: Run plugin tests
        run: |
          docker exec qgis-testing-environment bash -c "cd /tests_directory \
          && python3 -m coverage run -m unittest discover arches_project/tests

      - name: Run coverage
        run: |
          docker exec qgis-testing-environment bash -c "cd /tests_directory \
          && python3 -m coverage report -m"

  build_feature_branch:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        # Use LTR and latest release
        qgis_version: [3.40.11, 3.44.3]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Arches
        uses: ./.github/actions/build-arches-environment

      - name: Set up QGIS ${{ matrix.qgis_version }}
        uses: ./.github/actions/build-qgis-environment
        with:
          qgis_version: ${{ matrix.qgis_version }}

      - name: Run black formatting
        run: |
          docker exec qgis-testing-environment bash -c "cd /tests_directory/arches_project && pre-commit run --all-files --verbose"

      - name: Run plugin tests
        run: |
          docker exec qgis-testing-environment bash -c "cd /tests_directory \
          && python3 -m coverage run -m unittest discover arches_project/tests

      - name: Run coverage
        run: |
          docker exec qgis-testing-environment bash -c "cd /tests_directory \
          && python3 -m coverage report -m"
